# Generated by Django 5.0.3 on 2024-03-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0005_alter_useraccount_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                ],
                default="GBP",
                max_length=3,
            ),
        ),
    ]
