# Generated by Django 5.0.3 on 2024-03-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0006_alter_useraccount_currency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="amount",
            new_name="receivedAmount",
        ),
    ]
