# Generated by Django 5.0.3 on 2024-03-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0007_rename_amount_transaction_receivedamount"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="sentAmount",
            field=models.DecimalField(decimal_places=2, default=-0.0, max_digits=10),
        ),
    ]
