# Generated by Django 5.0.3 on 2024-03-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0008_transaction_sentamount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="sentAmount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
