# Generated by Django 5.0.3 on 2024-05-03 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0015_alter_moneyrequest_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moneyrequest",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 3, 13, 43, 20, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 3, 13, 43, 20, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
