# Generated by Django 5.0.3 on 2024-05-03 13:25

import payapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0016_alter_moneyrequest_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moneyrequest",
            name="timestamp",
            field=models.DateTimeField(
                default=payapp.models.get_safe_current_timestamp
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(
                default=payapp.models.get_safe_current_timestamp
            ),
        ),
    ]
